import { useState } from 'react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { Link, Route, Router as WouterRouter, Switch, useLocation, useParams } from 'wouter';
import { ArrowRight, BarChart3, Bell, BookOpen, BrainCircuit, Check, ChevronRight, CircleHelp, Clock3, CloudUpload, Compass, FileCheck2, Flower2, Gauge, Goal, GraduationCap, Leaf, LineChart, LogIn, MessageCircle, MoreHorizontal, Network, Play, Plus, RotateCcw, Search, Send, Settings2, ShieldCheck, Sparkles, Sprout, Target, TrendingUp, Upload, Users, X, Zap } from 'lucide-react';
import { useGetAchievements, useGetAnalytics, useGetCompetency, useGetCourse, useGetCourses, useGetDashboard, useGetGarden, useGetIntegrations, useGetProfile, useGetRecommendations, useGetSkillDna, useGenerateQuiz, useGetQuiz, useLogin, useRecordLearningTime, useSubmitAssessment, useSubmitQuiz } from '@workspace/api-client-react';
import { type ReactNode } from 'react';
import { ErrorBoundary } from '@/components/error-boundary';
import NotFound from '@/pages/not-found';

const queryClient = new QueryClient();

const nav = [
  { label: 'Overview', href: '/dashboard', icon: Gauge },
  { label: 'Competency twin', href: '/competency', icon: BrainCircuit },
  { label: 'Skill gaps', href: '/skill-gaps', icon: Target },
  { label: 'Learning path', href: '/learning-path', icon: RouteIcon },
  { label: 'Skill garden', href: '/skill-garden', icon: Flower2 },
  { label: 'Skill DNA', href: '/skill-dna', icon: Network },
  { label: 'Course catalogue', href: '/courses', icon: BookOpen },
];
const workspace = [
  { label: 'AI assistant', href: '/ai-assistant', icon: MessageCircle },
  { label: 'Achievements', href: '/achievements', icon: ShieldCheck },
  { label: 'Trainer workspace', href: '/trainer', icon: GraduationCap },
  { label: 'Workforce analytics', href: '/analytics', icon: BarChart3 },
];

function RouteIcon(props: { size?: number; strokeWidth?: number }) { return <Compass {...props} />; }
function Button({ children, onClick, variant = 'primary', className = '', type = 'button', disabled = false }: { children: ReactNode; onClick?: () => void; variant?: 'primary' | 'quiet' | 'outline' | 'coral'; className?: string; type?: 'button' | 'submit'; disabled?: boolean }) {
  const styles = { primary: 'bg-primary text-primary-foreground hover:opacity-90', quiet: 'bg-secondary/70 text-secondary-foreground hover:bg-secondary', outline: 'border border-border bg-card text-foreground hover:border-primary/50', coral: 'bg-accent text-accent-foreground hover:opacity-90' };
  return <button data-testid="button-action" type={type} onClick={onClick} disabled={disabled} className={`inline-flex items-center justify-center gap-2 rounded-lg px-4 py-2.5 text-sm font-semibold transition-transform duration-200 hover:-translate-y-0.5 disabled:cursor-not-allowed disabled:opacity-50 disabled:hover:translate-y-0 ${styles[variant]} ${className}`}>{children}</button>;
}
function Badge({ children, tone = 'muted' }: { children: ReactNode; tone?: 'muted' | 'coral' | 'gold' | 'teal' }) {
  const colors = { muted: 'bg-muted text-muted-foreground', coral: 'bg-accent/15 text-accent', gold: 'bg-chart-3/20 text-primary', teal: 'bg-primary/10 text-primary' };
  return <span className={`inline-flex items-center rounded-full px-2.5 py-1 text-[11px] font-semibold tracking-wide ${colors[tone]}`}>{children}</span>;
}
function Panel({ children, className = '', tint = '' }: { children: ReactNode; className?: string; tint?: string }) {
  return <section className={`rounded-2xl border border-card-border bg-card shadow-soft ${tint} ${className}`}>{children}</section>;
}
function SectionTitle({ eyebrow, title, detail, action }: { eyebrow?: string; title: string; detail?: string; action?: ReactNode }) {
  return <div className="mb-5 flex items-end justify-between gap-4"><div><div className="mb-1 font-mono text-[10px] uppercase tracking-[.18em] text-muted-foreground">{eyebrow}</div><h2 className="font-display text-3xl leading-none text-foreground">{title}</h2>{detail && <p className="mt-2 text-sm text-muted-foreground">{detail}</p>}</div>{action}</div>;
}
function Loading({ label = 'Tuning your workspace' }: { label?: string }) {
  return <div className="space-y-4" data-testid="status-loading"><div className="h-32 animate-pulse-soft rounded-2xl bg-muted" /><div className="grid gap-4 md:grid-cols-3"><div className="h-28 animate-pulse-soft rounded-2xl bg-muted" /><div className="h-28 animate-pulse-soft rounded-2xl bg-muted" /><div className="h-28 animate-pulse-soft rounded-2xl bg-muted" /></div><p className="font-mono text-xs text-muted-foreground">{label}...</p></div>;
}
function ErrorState({ retry }: { retry?: () => void }) { return <Panel className="p-8 text-center"><X className="mx-auto mb-3 text-destructive" /><h3 className="font-display text-2xl">The mesh is quiet for a moment.</h3><p className="mx-auto mt-2 max-w-md text-sm text-muted-foreground">We could not connect to your learning workspace. Your progress is safe.</p>{retry && <Button className="mt-5" variant="outline" onClick={retry}><RotateCcw size={15} /> Try again</Button>}</Panel>; }
function Avatar({ initials = 'PS', large = false }: { initials?: string; large?: boolean }) { return <div className={`${large ? 'h-16 w-16 text-xl' : 'h-9 w-9 text-xs'} flex shrink-0 items-center justify-center rounded-full bg-accent font-semibold text-accent-foreground ring-4 ring-accent/10`}>{initials}</div>; }
function ProgressBar({ value, color = 'bg-accent' }: { value: number; color?: string }) { return <div className="h-2 overflow-hidden rounded-full bg-muted"><div className={`h-full rounded-full ${color} transition-all duration-500`} style={{ width: `${Math.min(value, 100)}%` }} /></div>; }
function Ring({ value, label, size = 126 }: { value: number; label: string; size?: number }) { const deg = `${Math.min(value, 100) * 3.6}deg`; return <div className="relative grid place-items-center rounded-full" style={{ width: size, height: size, background: `conic-gradient(hsl(var(--accent)) ${deg}, hsl(var(--muted)) 0)` }}><div className="grid place-items-center rounded-full bg-card" style={{ width: size - 18, height: size - 18 }}><strong className="font-display text-3xl">{value}</strong><span className="font-mono text-[9px] uppercase tracking-wider text-muted-foreground">{label}</span></div></div>; }
function Sparkline({ values, color = 'hsl(var(--accent))' }: { values: number[]; color?: string }) { const max = Math.max(...values, 1); return <div className="flex h-20 items-end gap-1.5">{values.map((v, i) => <div key={i} className="flex-1 rounded-t-sm opacity-90 transition-all hover:opacity-100" style={{ height: `${Math.max(10, (v / max) * 100)}%`, backgroundColor: color }} />)}</div>; }

function Shell({ children }: { children: ReactNode }) {
  const [location] = useLocation();
  const [open, setOpen] = useState(false);
  const profile = useGetProfile();
  const person = profile.data;
  return <div className="min-h-[100dvh] bg-background">
    <aside className={`fixed inset-y-0 left-0 z-40 flex w-[254px] flex-col border-r border-sidebar-border bg-sidebar px-4 py-5 text-sidebar-foreground transition-transform duration-300 md:translate-x-0 ${open ? 'translate-x-0' : '-translate-x-full'}`}>
      <div className="flex items-center gap-3 px-3 pb-8"><div className="grid h-10 w-10 place-items-center rounded-xl bg-sidebar-primary text-sidebar-primary-foreground"><Network size={21} /></div><div><div className="font-display text-2xl leading-none">MindMesh</div><div className="mt-1 font-mono text-[9px] uppercase tracking-[.18em] opacity-50">Growth intelligence</div></div></div>
      <nav className="space-y-1">{nav.map(item => <NavItem key={item.href} item={item} active={location === item.href} />)}</nav>
      <div className="my-6 border-t border-sidebar-border" />
      <div className="mb-2 px-3 font-mono text-[9px] uppercase tracking-[.18em] opacity-40">Workspace</div>
      <nav className="space-y-1">{workspace.map(item => <NavItem key={item.href} item={item} active={location === item.href} />)}</nav>
      <div className="mt-auto rounded-xl bg-sidebar-accent p-3"><div className="flex items-center gap-2"><Sparkles size={15} className="text-sidebar-primary" /><span className="text-xs font-semibold">Daily signal</span></div><p className="mt-2 text-xs leading-relaxed opacity-60">One focused session today will move your critical gap.</p><Link href="/assessment" className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-sidebar-primary">Check in <ArrowRight size={12} /></Link></div>
      <Link href="/profile" className="mt-4 flex items-center gap-3 rounded-xl px-3 py-3 transition-colors hover:bg-sidebar-accent"><Avatar initials={person?.avatarInitials ?? 'PS'} /><div className="min-w-0"><div className="truncate text-xs font-semibold">{person?.name ?? 'Priya Sharma'}</div><div className="truncate text-[10px] opacity-50">{person?.designation ?? 'Statistical Officer'}</div></div><Settings2 size={15} className="ml-auto opacity-50" /></Link>
    </aside>
    {open && <button aria-label="Close menu" data-testid="button-close-menu" onClick={() => setOpen(false)} className="fixed inset-0 z-30 bg-primary/20 md:hidden" />}
    <div className="md:pl-[254px]"><header className="sticky top-0 z-20 flex h-[72px] items-center justify-between border-b border-border bg-background/90 px-5 backdrop-blur md:px-9"><button className="md:hidden" data-testid="button-open-menu" onClick={() => setOpen(true)}><MoreHorizontal /></button><div className="hidden items-center gap-2 text-xs text-muted-foreground md:flex"><span className="h-2 w-2 rounded-full bg-chart-4" /> Workspace synced <span className="text-border">/</span> FY 2024–25</div><div className="ml-auto flex items-center gap-3"><Link href="/ai-assistant" data-testid="link-ai-assistant" className="hidden items-center gap-2 rounded-full border border-border px-3 py-2 text-xs font-semibold text-muted-foreground hover:text-foreground sm:flex"><MessageCircle size={15} /> Ask your twin</Link><button data-testid="button-notifications" className="relative rounded-full p-2 text-muted-foreground hover:bg-muted"><Bell size={18} /><span className="absolute right-1.5 top-1.5 h-1.5 w-1.5 rounded-full bg-accent" /></button><Avatar initials={person?.avatarInitials ?? 'PS'} /></div></header><main className="mx-auto max-w-[1440px] px-5 py-7 md:px-9 lg:px-12">{children}</main></div>
  </div>;
}
function NavItem({ item, active }: { item: (typeof nav)[number]; active: boolean }) { const Icon = item.icon; return <Link href={item.href} data-testid={`link-${item.label.toLowerCase().replaceAll(' ', '-')}`} className={`group flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm transition-all ${active ? 'bg-sidebar-primary font-semibold text-sidebar-primary-foreground' : 'opacity-65 hover:bg-sidebar-accent hover:opacity-100'}`}><Icon size={17} strokeWidth={active ? 2.3 : 1.8} /><span>{item.label}</span>{active && <ChevronRight size={14} className="ml-auto" />}</Link>; }
function Page({ children, eyebrow, title, subtitle }: { children: ReactNode; eyebrow: string; title: ReactNode; subtitle?: string }) { return <div className="animate-rise"><div className="mb-8"><div className="mb-2 font-mono text-[10px] uppercase tracking-[.2em] text-accent">{eyebrow}</div><h1 className="font-display text-5xl leading-[.95] tracking-tight md:text-6xl">{title}</h1>{subtitle && <p className="mt-3 max-w-2xl text-sm leading-relaxed text-muted-foreground">{subtitle}</p>}</div>{children}</div>; }

function Dashboard() {
  const q = useGetDashboard();
  if (q.isLoading) return <Loading />;
  if (q.isError || !q.data) return <ErrorState retry={() => q.refetch()} />;
  const d = q.data;
  return <Page eyebrow="Tuesday · 08 October 2024" title={<>Good morning, <em className="text-accent">{d.profile.name.split(' ')[0]}</em>.</>} subtitle="Your competency twin has found a useful next step. A small, deliberate session today keeps the mesh growing.">
    <div className="grid gap-5 xl:grid-cols-[1.4fr_.8fr]">
      <Panel className="mesh-grid relative overflow-hidden p-6 md:p-8" tint="bg-primary text-primary-foreground"><div className="relative z-10 flex flex-col justify-between gap-8 md:flex-row"><div className="max-w-md"><Badge tone="gold">YOUR NEXT SIGNAL</Badge><h2 className="mt-4 font-display text-4xl leading-none md:text-5xl">Strengthen <span className="text-sidebar-primary">{d.competency.criticalGap}</span></h2><p className="mt-4 text-sm leading-relaxed opacity-70">{d.competency.insight}</p><Link href="/learning-path" data-testid="link-next-action" className="mt-7 inline-flex items-center gap-2 rounded-lg bg-sidebar-primary px-4 py-3 text-sm font-semibold text-sidebar-primary-foreground transition-transform hover:-translate-y-0.5">View my pathway <ArrowRight size={16} /></Link></div><div className="flex shrink-0 flex-col items-center justify-center rounded-2xl bg-white/10 p-5"><Ring value={d.competency.overall} label="overall" /><span className="mt-3 font-mono text-[10px] uppercase tracking-widest opacity-60">{d.competency.level}</span></div></div><div className="absolute -bottom-16 -right-6 h-48 w-48 rounded-full border border-sidebar-primary/20" /><div className="absolute -bottom-8 -right-16 h-48 w-48 rounded-full border border-sidebar-primary/10" /></Panel>
      <Panel className="flex flex-col justify-between p-6"><div className="flex items-center justify-between"><div><div className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">Learning rhythm</div><div className="mt-2 font-display text-4xl">{d.streak}<span className="ml-2 text-base font-sans text-muted-foreground">days</span></div></div><div className="rounded-xl bg-accent/15 p-3 text-accent"><Zap size={20} /></div></div><div className="mt-8"><div className="mb-2 flex justify-between text-xs"><span className="text-muted-foreground">This month</span><b>{d.learningHours} hours</b></div><ProgressBar value={Math.min(100, d.learningHours * 4)} /><p className="mt-3 text-xs leading-relaxed text-muted-foreground">You are building a steadier practice than 68% of your cohort.</p></div></Panel>
    </div>
    <div className="mt-10 grid gap-8 xl:grid-cols-[1.1fr_.9fr]"><div><SectionTitle eyebrow="PERSONALIZED BY YOUR TWIN" title="Keep the thread going" action={<Link href="/skill-gaps" className="text-xs font-semibold text-primary">See all gaps <ArrowRight className="ml-1 inline" size={13} /></Link>} /><div className="space-y-3">{d.recommendations.slice(0, 3).map((r: any, i: number) => <Link key={r.id} href={`/course/${r.id}`} data-testid={`card-recommendation-${r.id}`} className="group flex items-center gap-4 rounded-xl border border-card-border bg-card p-4 shadow-soft transition-all hover:-translate-y-0.5 hover:border-primary/30"><div className={`grid h-11 w-11 shrink-0 place-items-center rounded-xl ${i === 0 ? 'bg-accent/15 text-accent' : i === 1 ? 'bg-chart-3/20 text-primary' : 'bg-primary/10 text-primary'}`}>{i === 0 ? <Target size={19} /> : i === 1 ? <LineChart size={19} /> : <BookOpen size={19} />}</div><div className="min-w-0 flex-1"><div className="mb-1 flex flex-wrap items-center gap-2"><Badge tone={r.priority === 'High' ? 'coral' : 'muted'}>{r.priority} priority</Badge><span className="font-mono text-[10px] text-muted-foreground">{r.duration}</span></div><h3 className="truncate text-sm font-semibold">{r.title}</h3><p className="mt-1 truncate text-xs text-muted-foreground">{r.reason}</p></div><ArrowRight size={17} className="text-muted-foreground transition-transform group-hover:translate-x-1" /></Link>)}</div></div><div><SectionTitle eyebrow="RECENTLY IN MOTION" title="Your garden" action={<Link href="/skill-garden" className="text-xs font-semibold text-primary">Explore <ArrowRight className="ml-1 inline" size={13} /></Link>} /><Panel className="relative overflow-hidden p-5"><div className="flex items-center justify-between"><div><div className="font-display text-4xl">{d.garden.growth}%</div><p className="text-xs text-muted-foreground">garden growth</p></div><div className="text-right"><div className="font-display text-2xl">{d.garden.plantsUnlocked}</div><p className="text-xs text-muted-foreground">plants unlocked</p></div></div><ProgressBar value={d.garden.growth} color="bg-chart-4" /><div className="mt-5 grid grid-cols-3 gap-2">{d.garden.plants.slice(0, 3).map((p: any) => <div key={p.skill} className="rounded-xl bg-muted/70 p-3"><Sprout size={18} className="mb-4" style={{ color: p.color }} /><div className="truncate text-xs font-semibold">{p.skill}</div><div className="mt-1 font-mono text-[10px] text-muted-foreground">{p.growth}% grown</div></div>)}</div><div className="pointer-events-none absolute -bottom-12 -right-8 h-36 w-36 rounded-full bg-chart-4/10 blur-2xl" /></Panel></div></div>
    <div className="mt-10"><SectionTitle eyebrow="IN THE FLOW" title="Active courses" action={<Link href="/courses" className="text-xs font-semibold text-primary">Catalogue <ArrowRight className="ml-1 inline" size={13} /></Link>} /><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{d.courses.map((c: any) => <CourseCard key={c.id} course={c} />)}</div></div>
  </Page>;
}
function CourseCard({ course }: { course: any }) { return <Link href={`/course/${course.id}`} data-testid={`card-course-${course.id}`} className="group overflow-hidden rounded-2xl border border-card-border bg-card shadow-soft transition-all hover:-translate-y-1 hover:shadow-lift"><div className="h-2" style={{ backgroundColor: course.color }} /><div className="p-5"><div className="mb-7 flex items-start justify-between"><Badge tone="teal">{course.skill}</Badge><span className="font-mono text-[10px] text-muted-foreground">{course.duration}</span></div><h3 className="font-display text-2xl leading-none">{course.title}</h3><p className="mt-2 line-clamp-2 text-xs leading-relaxed text-muted-foreground">{course.description}</p><div className="mt-6"><div className="mb-2 flex justify-between text-[11px]"><span>{course.lessons} of {course.totalLessons} lessons</span><b>{course.progress}%</b></div><ProgressBar value={course.progress} color="bg-primary" /></div></div></Link>; }

function ProfilePage() { const q = useGetProfile(); if (q.isLoading) return <Loading />; if (q.isError || !q.data) return <ErrorState retry={() => q.refetch()} />; const p = q.data; return <Page eyebrow="Learner profile" title="Your working shape." subtitle="The context your competency twin uses to make learning personal, useful, and grounded in your next assignment."><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><Panel className="bg-primary p-7 text-primary-foreground"><Avatar initials={p.avatarInitials} large /><h2 className="mt-6 font-display text-4xl">{p.name}</h2><p className="mt-1 text-sm opacity-70">{p.designation}</p><div className="mt-8 space-y-4 border-t border-white/15 pt-5 text-sm"><div><span className="block font-mono text-[10px] uppercase tracking-wider opacity-50">Department</span>{p.department}</div><div><span className="block font-mono text-[10px] uppercase tracking-wider opacity-50">Role</span>{p.role}</div><div><span className="block font-mono text-[10px] uppercase tracking-wider opacity-50">Experience</span>{p.experience} years in public statistics</div></div></Panel><Panel className="p-7"><div className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">A direction worth keeping</div><blockquote className="mt-4 max-w-xl font-display text-4xl leading-tight">“{p.futureGoal}”</blockquote><div className="mt-8 grid gap-5 border-t border-border pt-5 sm:grid-cols-2"><div><span className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">Current assignment</span><p className="mt-2 text-sm font-semibold">{p.assignment}</p></div><div><span className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">Education</span><p className="mt-2 text-sm font-semibold">{p.education}</p></div></div><Button className="mt-8" variant="outline" onClick={() => window.alert('Profile editing will be available in the next workspace release.')}> <Settings2 size={15} /> Edit context</Button></Panel></div></Page>; }

function CompetencyPage() { const q = useGetCompetency(); if (q.isLoading) return <Loading />; if (q.isError || !q.data) return <ErrorState retry={() => q.refetch()} />; const c = q.data; return <Page eyebrow="AI competency twin" title="See the whole pattern." subtitle="Your twin reads across assessments, learning activity, and role context to show where capability is already strong—and where a little attention compounds."><div className="grid gap-5 xl:grid-cols-[.7fr_1.3fr]"><Panel className="flex flex-col items-center justify-center p-8 text-center"><Ring value={c.overall} label="overall" size={190} /><div className="mt-5"><Badge tone="gold">{c.level}</Badge><p className="mt-4 max-w-xs text-sm leading-relaxed text-muted-foreground">{c.insight}</p></div></Panel><Panel className="p-6"><SectionTitle eyebrow="CAPABILITY LANDSCAPE" title="Across your domains" detail="A balanced picture is more useful than one score." /><div className="space-y-6">{c.domains.map((d: any) => <div key={d.name}><div className="mb-2 flex justify-between text-sm"><span className="font-semibold">{d.name}</span><span className="font-mono text-xs text-muted-foreground">{d.score}</span></div><ProgressBar value={d.score} color="bg-chart-4" /></div>)}</div></Panel></div><div className="mt-8 grid gap-5 lg:grid-cols-2"><Panel className="p-6"><SectionTitle eyebrow="SIGNATURE STRENGTHS" title="What you bring" /><div className="flex flex-wrap gap-2">{c.strongSkills.map((s: string) => <Badge key={s} tone="teal"><Check size={13} className="mr-1" />{s}</Badge>)}</div></Panel><Panel className="border-accent/30 bg-accent/5 p-6"><SectionTitle eyebrow="ONE FOCUSED GAP" title={c.criticalGap} detail="This is the next high-leverage move in your pathway." /><div className="space-y-3">{c.gaps.map((s: string, i: number) => <div key={s} className="flex items-center gap-3 text-sm"><span className={`grid h-7 w-7 place-items-center rounded-full ${i === 0 ? 'bg-accent text-accent-foreground' : 'bg-accent/15 text-accent'}`}>0{i + 1}</span>{s}</div>)}</div><Link href="/assessment" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-accent">Refresh your twin <ArrowRight size={15} /></Link></Panel></div></Page>; }

function GapsPage() { const q = useGetRecommendations(); if (q.isLoading) return <Loading />; if (q.isError || !q.data) return <ErrorState retry={() => q.refetch()} />; return <Page eyebrow="Gap analysis" title="Choose the next useful thing." subtitle="Not every gap deserves equal attention. These actions are ranked by role relevance, momentum, and the shape of your current competency."><div className="grid gap-4">{q.data.map((r: any, i: number) => <Panel key={r.id} className={`grid gap-5 p-5 md:grid-cols-[52px_1fr_auto] md:items-center ${i === 0 ? 'border-accent/35 bg-accent/5' : ''}`}><div className="grid h-12 w-12 place-items-center rounded-2xl bg-primary text-primary-foreground"><span className="font-mono text-sm">0{i + 1}</span></div><div><div className="mb-2 flex flex-wrap items-center gap-2"><Badge tone={r.priority === 'High' ? 'coral' : 'gold'}>{r.priority} priority</Badge><Badge>{r.kind}</Badge><span className="font-mono text-[10px] text-muted-foreground">{r.duration}</span></div><h3 className="font-display text-3xl">{r.title}</h3><p className="mt-1 max-w-2xl text-sm text-muted-foreground">{r.reason}</p><div className="mt-3 flex items-center gap-3 text-xs text-muted-foreground"><span>{r.skill}</span><span className="text-border">→</span><span className="font-semibold text-primary">{r.targetLevel}</span></div></div><Link href={`/course/${r.id}`} className="inline-flex items-center justify-center gap-2 rounded-lg border border-border px-4 py-2.5 text-sm font-semibold hover:border-primary/40">Open action <ArrowRight size={15} /></Link></Panel>)}</div></Page>; }

function LearningPath() { const q = useGetRecommendations(); const integrations = useGetIntegrations(); if (q.isLoading || integrations.isLoading) return <Loading />; if (q.isError || !q.data) return <ErrorState retry={() => q.refetch()} />; return <Page eyebrow="Personalized pathway" title="A path with room to breathe." subtitle="Three short arcs, sequenced around your role—not a catalogue to finish."><div className="relative ml-3 border-l border-dashed border-primary/30 pl-8 md:ml-12 md:pl-12">{q.data.slice(0, 3).map((r: any, i: number) => <div key={r.id} className="relative mb-8 last:mb-0"><div className="absolute -left-[49px] grid h-8 w-8 place-items-center rounded-full border-4 border-background bg-primary font-mono text-xs text-primary-foreground md:-left-[65px]">{i + 1}</div><Panel className="p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><Badge tone={i === 0 ? 'coral' : 'muted'}>{i === 0 ? 'Now' : i === 1 ? 'Next' : 'Later'}</Badge><h2 className="mt-3 font-display text-3xl">{r.title}</h2></div><div className="text-right font-mono text-xs text-muted-foreground">{r.duration}<br />{r.provider}</div></div><p className="mt-3 max-w-2xl text-sm leading-relaxed text-muted-foreground">{r.reason}</p><div className="mt-5 flex flex-wrap items-center gap-3"><Link href={`/course/${r.id}`} className="inline-flex items-center gap-2 text-sm font-semibold text-primary">Start this arc <ArrowRight size={15} /></Link><span className="text-border">·</span><span className="text-xs text-muted-foreground">Moves {r.skill} toward {r.targetLevel}</span></div></Panel></div>)}</div><Panel className="mt-10 p-6"><div className="flex items-center gap-3"><div className="rounded-xl bg-chart-3/20 p-3 text-primary"><CloudUpload size={19} /></div><div><h3 className="font-display text-2xl">Connected learning sources</h3><p className="text-sm text-muted-foreground">Your pathway also checks public-sector learning ecosystems.</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-2">{integrations.data?.igot.slice(0, 2).map((x: any) => <div key={x.title} className="flex items-center justify-between rounded-xl bg-muted/60 p-4 text-sm"><span>{x.title}</span><Badge tone="teal">{x.status}</Badge></div>)}</div></Panel></Page>; }

function GardenPage() { const q = useGetGarden(); if (q.isLoading) return <Loading label="Planting your view" />; if (q.isError || !q.data) return <ErrorState retry={() => q.refetch()} />; const g = q.data; return <Page eyebrow="Skill garden" title="Capability, in season." subtitle="Every focused hour changes the landscape. Wander through the skills you are cultivating and notice what is ready to grow next."><div className="grid gap-5 md:grid-cols-4"><Stat value={`${g.growth}%`} label="garden growth" icon={<Sprout />} /><Stat value={`${g.totalHours}h`} label="learning invested" icon={<Clock3 />} /><Stat value={g.plantsUnlocked} label="plants unlocked" icon={<Flower2 />} /><Stat value={g.streak} label="day rhythm" icon={<Zap />} /></div><Panel className="mesh-grid mt-5 min-h-[480px] overflow-hidden p-6 md:p-10"><div className="flex items-start justify-between"><div><Badge tone="teal">LIVE LANDSCAPE</Badge><h2 className="mt-3 font-display text-4xl">The cultivated clearing</h2></div><div className="text-right"><div className="font-display text-3xl text-chart-4">{g.skillsCultivated}</div><div className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">skills in soil</div></div></div><div className="relative mx-auto mt-8 min-h-[300px] max-w-3xl">{g.plants.map((p: any) => <div key={p.skill} className="absolute -translate-x-1/2 -translate-y-1/2 text-center transition-transform hover:scale-110" style={{ left: `${p.x}%`, top: `${p.y}%` }}><div className="mx-auto grid h-16 w-16 place-items-center rounded-full border-4 bg-card shadow-lift" style={{ borderColor: p.color }}><Sprout size={26} style={{ color: p.color }} /></div><div className="mt-2 whitespace-nowrap text-xs font-semibold">{p.skill}</div><div className="font-mono text-[9px] text-muted-foreground">{p.growth}%</div></div>)}</div></Panel><div className="mt-5 rounded-xl border border-accent/25 bg-accent/5 p-5 text-sm"><span className="font-semibold">Recently grown:</span> {g.recentlyGrown}. Keep the rhythm gentle and regular.</div></Page>; }
function Stat({ value, label, icon }: { value: string | number; label: string; icon: ReactNode }) { return <Panel className="p-5"><div className="mb-5 flex items-center justify-between text-accent">{icon}</div><div className="font-display text-3xl">{value}</div><div className="mt-1 text-xs text-muted-foreground">{label}</div></Panel>; }

function DnaPage() { const q = useGetSkillDna(); if (q.isLoading) return <Loading />; if (q.isError || !q.data) return <ErrorState retry={() => q.refetch()} />; const d = q.data; return <Page eyebrow="Evolving skill DNA" title="Your genome is not fixed." subtitle="A living view of the range, depth, and direction of your professional capability."><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><Panel className="bg-primary p-7 text-primary-foreground"><div className="font-mono text-[10px] uppercase tracking-wider opacity-60">Diversity index</div><div className="mt-3 font-display text-8xl">{d.diversityScore}</div><p className="mt-2 text-sm leading-relaxed opacity-65">A broader skill genome makes your statistical practice more adaptive.</p><div className="mt-8 space-y-4 border-t border-white/15 pt-5"><div><span className="font-mono text-[10px] uppercase tracking-wider opacity-50">Strongest gene</span><div className="mt-1 text-lg">{d.strongestGene}</div></div><div><span className="font-mono text-[10px] uppercase tracking-wider opacity-50">Fastest growing</span><div className="mt-1 text-lg">{d.fastestGrowing}</div></div></div></Panel><Panel className="p-6"><SectionTitle eyebrow="GENE EXPRESSION" title="The current strand" /><div className="space-y-5">{d.genes.map((g: any) => <div key={g.skill}><div className="mb-2 flex items-center justify-between"><div><span className="text-sm font-semibold">{g.skill}</span><span className="ml-2 text-xs text-muted-foreground">{g.category}</span></div><span className="font-mono text-xs">{g.score}</span></div><ProgressBar value={g.score} color="bg-chart-4" /></div>)}</div></Panel></div><Panel className="mt-5 flex flex-wrap items-center justify-between gap-4 p-5"><div className="flex items-center gap-3"><Sparkles className="text-accent" size={20} /><div><div className="text-sm font-semibold">Recently added gene</div><div className="text-xs text-muted-foreground">{d.recentlyAdded}</div></div></div><Link href="/assessment" className="text-sm font-semibold text-primary">Update DNA <ArrowRight className="ml-1 inline" size={14} /></Link></Panel></Page>; }

function CoursesPage() { const q = useGetCourses(); const [filter, setFilter] = useState('All'); if (q.isLoading) return <Loading />; if (q.isError || !q.data) return <ErrorState retry={() => q.refetch()} />; const skills = ['All', ...Array.from(new Set(q.data.map((c: any) => c.skill)))]; const courses = filter === 'All' ? q.data : q.data.filter((c: any) => c.skill === filter); return <Page eyebrow="Course catalogue" title="Find your next thread." subtitle="Role-relevant learning, chosen for where you are now."><div className="mb-7 flex flex-wrap gap-2">{skills.map(s => <button key={s} data-testid={`button-filter-${s}`} onClick={() => setFilter(s)} className={`rounded-full px-4 py-2 text-xs font-semibold transition-colors ${filter === s ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground hover:bg-secondary'}`}>{s}</button>)}</div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{courses.map((c: any) => <CourseCard key={c.id} course={c} />)}</div>{courses.length === 0 && <Panel className="p-12 text-center"><Search className="mx-auto mb-3 text-muted-foreground" /><p className="text-sm text-muted-foreground">No courses in this strand yet.</p></Panel>}</Page>; }

function CourseDetailPage() { const { id = '' } = useParams(); const q = useGetCourse(id); const record = useRecordLearningTime(); const [logged, setLogged] = useState(false); if (q.isLoading) return <Loading />; if (q.isError || !q.data) return <ErrorState retry={() => q.refetch()} />; const c = q.data; return <Page eyebrow={`${c.provider} · ${c.skill}`} title={c.title} subtitle={c.description}><div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><div><Panel className="overflow-hidden"><div className="h-3" style={{ backgroundColor: c.color }} /><div className="p-6 md:p-8"><div className="flex flex-wrap gap-2"><Badge tone="teal">{c.skill}</Badge><Badge>{c.duration}</Badge><Badge>{c.totalLessons} lessons</Badge></div><div className="mt-8 flex items-end justify-between"><div><div className="font-display text-5xl">{c.progress}%</div><div className="text-xs text-muted-foreground">pathway complete</div></div><Button onClick={() => { record.mutate({ data: { courseId: c.id, minutes: 25 } }); setLogged(true); }} variant="coral"><Play size={15} /> Log 25 minutes</Button></div><div className="mt-4"><ProgressBar value={c.progress} /></div>{logged && <div className="mt-4 flex items-center gap-2 text-xs font-semibold text-chart-4"><Check size={14} /> Time recorded. Your garden has moved.</div>}</div></Panel><Panel className="mt-5 p-6"><SectionTitle eyebrow="WHY THIS MATTERS" title="Learning objectives" /> <div className="grid gap-3 md:grid-cols-2">{c.objectives.map((o: string, i: number) => <div key={o} className="flex gap-3 rounded-xl bg-muted/60 p-4 text-sm"><span className="font-mono text-accent">0{i + 1}</span>{o}</div>)}</div></Panel></div><Panel className="p-6"><SectionTitle eyebrow="THE PATH" title="Modules" detail={`${c.modules.filter((m: any) => m.completed).length} of ${c.modules.length} complete`} /><div className="space-y-2">{c.modules.map((m: any, i: number) => <div key={m.title} className="flex items-center gap-3 rounded-xl border border-transparent p-3 transition-colors hover:border-border hover:bg-muted/50"><div className={`grid h-8 w-8 place-items-center rounded-full ${m.completed ? 'bg-chart-4/20 text-chart-4' : 'bg-muted text-muted-foreground'}`}>{m.completed ? <Check size={15} /> : <span className="font-mono text-[10px]">{i + 1}</span>}</div><div className="min-w-0 flex-1"><div className="truncate text-sm font-semibold">{m.title}</div><div className="mt-1 flex items-center gap-1 text-[10px] text-muted-foreground"><Clock3 size={11} /> {m.duration}</div></div>{m.completed && <span className="font-mono text-[9px] uppercase text-chart-4">done</span>}</div>)}</div></Panel></div></Page>; }

function AssessmentPage() { const submit = useSubmitAssessment(); const [step, setStep] = useState(0); const [answers, setAnswers] = useState<number[]>([]); const [result, setResult] = useState<any>(null); const questions = ['How confident are you designing a reliable sampling approach?', 'How often do you communicate statistical findings to non-technical teams?', 'How ready are you to use digital tools in an official statistics workflow?']; if (result) return <Page eyebrow="Assessment complete" title="A sharper starting point." subtitle={result.message}><Panel className="mx-auto max-w-2xl p-8"><div className="flex flex-col items-center text-center"><Ring value={result.score} label="score" size={170} /><Badge tone="gold">{result.level}</Badge><div className="mt-8 grid w-full gap-4 text-left md:grid-cols-2"><div className="rounded-xl bg-chart-4/10 p-4"><div className="font-mono text-[10px] uppercase tracking-wider text-chart-4">Strong signals</div><p className="mt-2 text-sm">{result.strong.join(', ')}</p></div><div className="rounded-xl bg-accent/10 p-4"><div className="font-mono text-[10px] uppercase tracking-wider text-accent">Room to grow</div><p className="mt-2 text-sm">{result.improve.join(', ')}</p></div></div><Link href="/learning-path" className="mt-8 inline-flex items-center gap-2 rounded-lg bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">Build my pathway <ArrowRight size={16} /></Link></div></Panel></Page>; return <Page eyebrow="Competency check-in" title="Let the twin listen." subtitle="Three quick reflections. There are no wrong answers—just a more honest map for your next move."><Panel className="mx-auto max-w-2xl p-6 md:p-10"><div className="mb-8 flex items-center justify-between"><span className="font-mono text-xs text-muted-foreground">0{step + 1} / 0{questions.length}</span><div className="flex gap-1">{questions.map((_, i) => <div key={i} className={`h-1 w-12 rounded-full ${i <= step ? 'bg-accent' : 'bg-muted'}`} />)}</div></div><h2 className="font-display text-4xl leading-tight">{questions[step]}</h2><div className="mt-10 space-y-3">{['I am building this capability', 'I can do this with some support', 'I can confidently guide others'].map((option, i) => <button key={option} data-testid={`button-answer-${i}`} onClick={() => { const next = [...answers, i + 1]; setAnswers(next); if (step < questions.length - 1) setStep(step + 1); else submit.mutate({ data: { answers: next } }, { onSuccess: setResult }); }} className="flex w-full items-center gap-4 rounded-xl border border-border p-4 text-left text-sm transition-all hover:border-accent hover:bg-accent/5"><span className="grid h-8 w-8 place-items-center rounded-full bg-muted font-mono text-xs">{i + 1}</span>{option}<ChevronRight size={16} className="ml-auto text-muted-foreground" /></button>)}</div><p className="mt-8 text-center text-xs text-muted-foreground">Your answers are used only to tune your learning map.</p></Panel></Page>; }

function AssistantPage() { const [messages, setMessages] = useState([{ from: 'twin', text: 'I am here. What would make your next learning session more useful?' }]); const [input, setInput] = useState(''); const send = () => { if (!input.trim()) return; const text = input.trim(); setMessages(m => [...m, { from: 'you', text }, { from: 'twin', text: 'I would start with a 25-minute practice on your critical gap, then reflect on one example from your current assignment.' }]); setInput(''); }; return <Page eyebrow="Learning support" title="Ask the mesh." subtitle="A quiet thinking partner for the moments between courses, assignments, and new questions."><div className="mx-auto max-w-3xl"><Panel className="overflow-hidden"><div className="flex items-center gap-3 border-b border-border bg-primary p-5 text-primary-foreground"><div className="grid h-10 w-10 place-items-center rounded-xl bg-sidebar-primary text-sidebar-primary-foreground"><BrainCircuit size={21} /></div><div><div className="font-semibold">MindMesh twin</div><div className="flex items-center gap-1 text-[11px] opacity-60"><span className="h-1.5 w-1.5 rounded-full bg-chart-4" /> Context-aware support</div></div></div><div className="min-h-[360px] space-y-5 bg-card p-5 md:p-8">{messages.map((m, i) => <div key={i} className={`flex ${m.from === 'you' ? 'justify-end' : 'justify-start'}`}><div className={`max-w-[80%] rounded-2xl px-4 py-3 text-sm leading-relaxed ${m.from === 'you' ? 'rounded-br-sm bg-accent text-accent-foreground' : 'rounded-bl-sm bg-muted'}`}>{m.text}</div></div>)}</div><div className="border-t border-border p-4"><div className="flex gap-2"><input data-testid="input-assistant" value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => e.key === 'Enter' && send()} placeholder="Ask about a concept, course, or next step..." className="min-w-0 flex-1 rounded-lg border border-input bg-background px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-ring" /><Button onClick={send}><Send size={15} /> Send</Button></div></div></Panel><div className="mt-4 flex flex-wrap gap-2">{['Explain my critical gap', 'Plan a 25-minute session', 'Connect this to my assignment'].map(s => <button key={s} data-testid={`button-prompt-${s}`} onClick={() => { setInput(s); }} className="rounded-full border border-border px-3 py-2 text-xs text-muted-foreground hover:border-primary/40 hover:text-foreground">{s}</button>)}</div></div></Page>; }

function AchievementsPage() { const q = useGetAchievements(); if (q.isLoading) return <Loading />; if (q.isError || !q.data) return <ErrorState retry={() => q.refetch()} />; const a = q.data; return <Page eyebrow="Shield progression" title="Quiet consistency counts." subtitle="Shields are not trophies. They are small records of the practice you are building."><Panel className="bg-primary p-7 text-primary-foreground"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-center"><div><Badge tone="gold">CURRENT SHIELD</Badge><h2 className="mt-4 font-display text-5xl">{a.current}</h2><p className="mt-2 text-sm opacity-60">{a.currentTier} tier · next: {a.next}</p></div><div className="grid h-28 w-28 place-items-center rounded-full border-2 border-sidebar-primary/50 bg-sidebar-primary/10"><ShieldCheck size={48} className="text-sidebar-primary" /></div></div><div className="mt-8"><div className="mb-2 flex justify-between text-xs opacity-70"><span>Progress to {a.next}</span><span>{a.nextProgress}%</span></div><ProgressBar value={a.nextProgress} color="bg-sidebar-primary" /></div></Panel><div className="mt-6 grid gap-4 md:grid-cols-2">{a.shields.map((s: any) => <Panel key={s.name} className={`p-5 ${!s.unlocked ? 'opacity-65' : ''}`}><div className="flex items-start justify-between"><div className={`grid h-12 w-12 place-items-center rounded-xl ${s.unlocked ? 'bg-chart-3/20 text-primary' : 'bg-muted text-muted-foreground'}`}><ShieldCheck size={24} /></div><Badge tone={s.unlocked ? 'teal' : 'muted'}>{s.unlocked ? 'Unlocked' : `${s.progress}%`}</Badge></div><h3 className="mt-5 font-display text-2xl">{s.name}</h3><p className="mt-1 text-xs text-muted-foreground">{s.requirement}</p>{!s.unlocked && <div className="mt-4"><ProgressBar value={s.progress} /></div>}</Panel>)}</div></Page>; }

function AnalyticsPage() { const q = useGetAnalytics(); if (q.isLoading) return <Loading />; if (q.isError || !q.data) return <ErrorState retry={() => q.refetch()} />; const a = q.data; return <Page eyebrow="Workforce intelligence" title="See the system, clearly." subtitle="A department-level view of capability, momentum, and the gaps worth resourcing next."><div className="grid gap-4 md:grid-cols-4"><Stat value={a.totalLearners.toLocaleString()} label="active learners" icon={<Users />} /><Stat value={a.averageCompetency} label="average competency" icon={<Gauge />} /><Stat value={`${a.completionRate}%`} label="completion rate" icon={<Check />} /><Stat value={`${a.learningHours}h`} label="learning invested" icon={<Clock3 />} /></div><div className="mt-5 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><Panel className="p-6"><SectionTitle eyebrow="CAPABILITY TREND" title="Momentum over time" /><Sparkline values={a.trend.map((t: any) => t.score)} color="hsl(var(--primary))" /><div className="mt-3 flex justify-between font-mono text-[10px] text-muted-foreground">{a.trend.map((t: any) => <span key={t.month}>{t.month}</span>)}</div></Panel><Panel className="p-6"><SectionTitle eyebrow="TOP PRIORITY" title="Workforce gaps" />{a.gaps.slice(0, 5).map((g: any) => <div key={g.skill} className="mb-4 last:mb-0"><div className="mb-1 flex justify-between text-xs"><span>{g.skill}</span><span className="font-mono">{g.percentage}%</span></div><ProgressBar value={g.percentage} color="bg-accent" /></div>)}</Panel></div><Panel className="mt-5 p-6"><SectionTitle eyebrow="DEPARTMENT LENS" title="Capability by team" /><div className="space-y-4">{a.departments.map((d: any) => <div key={d.name} className="grid items-center gap-3 md:grid-cols-[180px_1fr_80px]"><div className="text-sm font-semibold">{d.name}</div><ProgressBar value={d.score} color="bg-chart-4" /><div className="font-mono text-xs text-muted-foreground">{d.learners} learners</div></div>)}</div></Panel></Page>; }

function LoginPage() { const login = useLogin(); const [, setLocation] = useLocation(); const [email, setEmail] = useState('priya.sharma@mospi.gov.in'); const [password, setPassword] = useState('mindmesh-demo'); return <div className="mesh-grid flex min-h-[100dvh] items-center justify-center bg-primary p-5"><div className="grid w-full max-w-5xl overflow-hidden rounded-3xl bg-card shadow-lift md:grid-cols-2"><div className="hidden flex-col justify-between bg-sidebar p-10 text-sidebar-foreground md:flex"><div><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-sidebar-primary text-sidebar-primary-foreground"><Network /></div><span className="font-display text-3xl">MindMesh</span></div><div className="mt-24 max-w-sm"><div className="font-mono text-[10px] uppercase tracking-[.2em] text-sidebar-primary">Competency intelligence</div><h1 className="mt-4 font-display text-6xl leading-[.9]">Grow the system. <em className="text-sidebar-primary">Grow yourself.</em></h1><p className="mt-6 text-sm leading-relaxed opacity-60">A learning command center for India’s official statistical workforce.</p></div></div><div className="font-mono text-[10px] opacity-40">SECURE DEMO ENVIRONMENT · MOSPI</div></div><div className="p-7 md:p-12"><div className="mb-12 md:hidden"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-primary text-primary-foreground"><Network /></div><span className="font-display text-3xl">MindMesh</span></div></div><div className="font-mono text-[10px] uppercase tracking-[.2em] text-accent">Welcome back</div><h2 className="mt-3 font-display text-4xl">Enter your workspace.</h2><p className="mt-3 text-sm text-muted-foreground">Use the demo learner role to explore the mesh.</p><form className="mt-9 space-y-5" onSubmit={e => { e.preventDefault(); login.mutate({ data: { email, password } }, { onSuccess: () => setLocation('/dashboard') }); }}><label className="block text-sm font-semibold">Official email<input data-testid="input-email" value={email} onChange={e => setEmail(e.target.value)} className="mt-2 w-full rounded-lg border border-input bg-background px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-ring" /></label><label className="block text-sm font-semibold">Access phrase<input data-testid="input-password" type="password" value={password} onChange={e => setPassword(e.target.value)} className="mt-2 w-full rounded-lg border border-input bg-background px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-ring" /></label><Button type="submit" className="w-full" disabled={login.isPending}>{login.isPending ? 'Opening workspace...' : <><LogIn size={16} /> Enter demo workspace</>}</Button></form>{login.isError && <p className="mt-4 text-sm text-destructive">That demo login did not work. Please try again.</p>}<p className="mt-8 text-center text-xs text-muted-foreground">By entering, you agree to the demo workspace terms.</p></div></div></div>; }

function MaterialsPage() { const [uploaded, setUploaded] = useState(false); return <Page eyebrow="Trainer workspace" title="Put good material in reach." subtitle="A considered home for the documents, examples, and field knowledge that help teams learn in context."><div className="grid gap-5 lg:grid-cols-[1fr_.8fr]"><Panel className="border-dashed p-8 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-accent/15 text-accent"><Upload size={24} /></div><h2 className="mt-5 font-display text-3xl">Add learning material</h2><p className="mx-auto mt-2 max-w-sm text-sm text-muted-foreground">PDF, DOCX, or a plain text note. The quiz generator will use it as its source of truth.</p><Button className="mt-6" variant="coral" onClick={() => setUploaded(true)}><Plus size={15} /> Choose a file</Button>{uploaded && <div className="mx-auto mt-5 flex max-w-sm items-center gap-3 rounded-xl bg-chart-4/10 p-3 text-left"><FileCheck2 className="text-chart-4" size={20} /><div className="text-xs"><b>Sampling_frame_guidance.pdf</b><div className="text-muted-foreground">Ready to generate from · 2.4 MB</div></div><Check className="ml-auto text-chart-4" size={16} /></div>}</Panel><Panel className="p-6"><SectionTitle eyebrow="RECENT MATERIAL" title="Source shelf" /><div className="space-y-3">{['District estimation handbook', 'Field supervision notes', 'Sampling frame guidance'].map((x, i) => <div key={x} className="flex items-center gap-3 rounded-xl bg-muted/60 p-3"><div className="rounded-lg bg-card p-2 text-accent"><BookOpen size={16} /></div><div className="text-sm font-semibold">{x}</div><span className="ml-auto font-mono text-[10px] text-muted-foreground">{i + 2}d ago</span></div>)}</div></Panel></div><Panel className="mt-5 p-6"><SectionTitle eyebrow="NEXT" title="Turn material into practice." action={<Link href="/quiz-generator" className="text-sm font-semibold text-primary">Open quiz generator <ArrowRight className="ml-1 inline" size={14} /></Link>} /><p className="max-w-2xl text-sm leading-relaxed text-muted-foreground">Generate a first draft, review every question, and publish only what reflects the nuance of official statistics work.</p></Panel></Page>; }

function QuizGeneratorPage() { const generate = useGenerateQuiz(); const [title, setTitle] = useState('Sampling frames and coverage'); const [content, setContent] = useState('A sampling frame is the operational list of units from which a sample is drawn. Coverage error occurs when the frame excludes eligible units or includes ineligible units.'); const [quiz, setQuiz] = useState<any>(null); return <Page eyebrow="Trainer tools" title="Make practice from knowledge." subtitle="Start with a source. Leave with a reviewable quiz draft."><Panel className="max-w-3xl p-6 md:p-8"><label className="block text-sm font-semibold">Material title<input data-testid="input-quiz-title" value={title} onChange={e => setTitle(e.target.value)} className="mt-2 w-full rounded-lg border border-input bg-background px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-ring" /></label><label className="mt-5 block text-sm font-semibold">Source content<textarea data-testid="input-quiz-content" value={content} onChange={e => setContent(e.target.value)} rows={7} className="mt-2 w-full resize-none rounded-lg border border-input bg-background px-4 py-3 text-sm leading-relaxed outline-none focus:ring-2 focus:ring-ring" /></label><Button className="mt-5" variant="coral" disabled={generate.isPending} onClick={() => generate.mutate({ data: { title, content } }, { onSuccess: setQuiz })}><Sparkles size={15} /> {generate.isPending ? 'Generating draft...' : 'Generate quiz draft'}</Button></Panel>{quiz && <Panel className="mt-5 p-6"><SectionTitle eyebrow="GENERATED DRAFT" title={quiz.title} detail={`${quiz.totalQuestions} questions · Review before publishing`} />{quiz.questions.map((x: any, i: number) => <div key={x.id} className="mb-4 rounded-xl border border-border p-4"><div className="flex gap-3"><span className="font-mono text-xs text-accent">0{i + 1}</span><div className="text-sm font-semibold">{x.question}</div><Badge tone="gold">{x.difficulty}</Badge></div><div className="mt-3 grid gap-2 pl-7 md:grid-cols-2">{x.options.map((o: string, j: number) => <div key={o} className={`rounded-lg px-3 py-2 text-xs ${j === x.answer ? 'bg-chart-4/10 font-semibold text-chart-4' : 'bg-muted'}`}>{o}</div>)}</div></div>)}<Link href={`/quiz/${quiz.id}`} data-testid="link-review-quiz" className="mt-2 inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground">Review in quiz mode <ArrowRight size={15} /></Link></Panel>}</Page>; }

function QuizPage() { const { id = '' } = useParams(); const q = useGetQuiz(id); const submit = useSubmitQuiz(); const [answers, setAnswers] = useState<number[]>([]); const [result, setResult] = useState<any>(null); if (q.isLoading) return <Loading label="Opening assessment" />; if (q.isError || !q.data) return <ErrorState retry={() => q.refetch()} />; const quiz = q.data; if (result) return <Page eyebrow="Quiz complete" title="Your feedback is ready." subtitle={result.feedback}><Panel className="mx-auto max-w-xl p-8 text-center"><Ring value={Math.round((result.correct / result.total) * 100)} label="score" size={160} /><div className="mt-5 font-display text-3xl">{result.correct} of {result.total} correct</div><p className="mt-3 text-sm text-muted-foreground">{result.skillUpdate}</p><Link href="/feedback" className="mt-7 inline-flex items-center gap-2 rounded-lg bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">See learning feedback <ArrowRight size={16} /></Link></Panel></Page>; return <Page eyebrow="Knowledge check" title={quiz.title} subtitle={`${quiz.totalQuestions} questions · Take your time. Accuracy is more useful than speed.`}><Panel className="mx-auto max-w-3xl p-6 md:p-8">{quiz.questions.map((x: any, i: number) => <div key={x.id} className="border-b border-border py-6 first:pt-0 last:border-0"><div className="flex gap-3"><span className="font-mono text-xs text-accent">0{i + 1}</span><h2 className="font-display text-2xl">{x.question}</h2></div><div className="mt-4 grid gap-2 pl-7">{x.options.map((o: string, j: number) => <button key={o} data-testid={`button-option-${x.id}-${j}`} onClick={() => setAnswers(a => { const next = [...a]; next[i] = j; return next; })} className={`rounded-xl border p-3 text-left text-sm transition-colors ${answers[i] === j ? 'border-accent bg-accent/10' : 'border-border hover:border-primary/40'}`}><span className="mr-3 font-mono text-xs text-muted-foreground">{String.fromCharCode(65 + j)}</span>{o}</button>)}</div></div>)}<Button className="mt-6" disabled={answers.length !== quiz.questions.length || submit.isPending} onClick={() => submit.mutate({ id, data: { answers } }, { onSuccess: setResult })}>{submit.isPending ? 'Reviewing...' : 'Submit answers'} <ArrowRight size={15} /></Button></Panel></Page>; }

function FeedbackPage() { return <Page eyebrow="Learning reflection" title="Let the insight settle." subtitle="Feedback is most useful when it changes what you notice next."><div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><Panel className="p-7"><Badge tone="gold">AI REFLECTION</Badge><h2 className="mt-5 font-display text-4xl">You are closer than the score suggests.</h2><p className="mt-5 text-sm leading-relaxed text-muted-foreground">Your responses show a reliable grasp of the core idea. The next lift is applying it to a less tidy field context, where frame quality and judgement meet.</p><div className="mt-8 border-l-2 border-accent pl-4 text-sm italic">“Try explaining coverage error using one example from your current assignment.”</div><Link href="/ai-assistant" className="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-primary">Discuss this with your twin <ArrowRight size={15} /></Link></Panel><Panel className="p-7"><SectionTitle eyebrow="ONE NEXT PRACTICE" title="Explain it simply." /><div className="rounded-2xl bg-muted p-5"><div className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">Prompt</div><p className="mt-3 font-display text-2xl leading-tight">How would you explain this idea to a district officer in two minutes?</p></div><Button className="mt-5" variant="outline" onClick={() => window.alert('Reflection saved to your learning journal.')}>Save reflection <Check size={15} /></Button></Panel></div></Page>; }

function TrainerPage() { return <Page eyebrow="Trainer workspace" title="Make learning travel." subtitle="See what your cohort needs, prepare material, and make every session feel close to the work."><div className="grid gap-5 md:grid-cols-3"><Link href="/materials" className="group rounded-2xl border border-card-border bg-card p-6 shadow-soft transition-all hover:-translate-y-1"><CloudUpload className="text-accent" /><h2 className="mt-7 font-display text-3xl">Material shelf</h2><p className="mt-2 text-sm text-muted-foreground">Upload and organise source material for your team.</p><ArrowRight className="mt-8 text-primary transition-transform group-hover:translate-x-1" /></Link><Link href="/quiz-generator" className="group rounded-2xl border border-card-border bg-card p-6 shadow-soft transition-all hover:-translate-y-1"><FileCheck2 className="text-chart-4" /><h2 className="mt-7 font-display text-3xl">Quiz studio</h2><p className="mt-2 text-sm text-muted-foreground">Turn expertise into reviewable, contextual questions.</p><ArrowRight className="mt-8 text-primary transition-transform group-hover:translate-x-1" /></Link><Link href="/analytics" className="group rounded-2xl border border-card-border bg-card p-6 shadow-soft transition-all hover:-translate-y-1"><BarChart3 className="text-primary" /><h2 className="mt-7 font-display text-3xl">Cohort signal</h2><p className="mt-2 text-sm text-muted-foreground">Find the patterns beneath the scores.</p><ArrowRight className="mt-8 text-primary transition-transform group-hover:translate-x-1" /></Link></div><Panel className="mt-6 p-6"><SectionTitle eyebrow="TRAINER NOTE" title="Context is a learning technology." /><p className="max-w-2xl text-sm leading-relaxed text-muted-foreground">The best material names the judgement behind the method. Add examples from the field, invite questions, and let the team see the work in the learning.</p></Panel></Page>; }

function AppRouter() {
  return <Switch><Route path="/login" component={LoginPage} /><Route><Shell><Switch><Route path="/" component={Dashboard} /><Route path="/dashboard" component={Dashboard} /><Route path="/profile" component={ProfilePage} /><Route path="/assessment" component={AssessmentPage} /><Route path="/competency" component={CompetencyPage} /><Route path="/skill-gaps" component={GapsPage} /><Route path="/learning-path" component={LearningPath} /><Route path="/skill-garden" component={GardenPage} /><Route path="/skill-dna" component={DnaPage} /><Route path="/courses" component={CoursesPage} /><Route path="/course/:id" component={CourseDetailPage} /><Route path="/ai-assistant" component={AssistantPage} /><Route path="/materials" component={MaterialsPage} /><Route path="/quiz-generator" component={QuizGeneratorPage} /><Route path="/quiz/:id" component={QuizPage} /><Route path="/feedback" component={FeedbackPage} /><Route path="/achievements" component={AchievementsPage} /><Route path="/trainer" component={TrainerPage} /><Route path="/admin" component={AnalyticsPage} /><Route path="/analytics" component={AnalyticsPage} /><Route component={NotFound} /></Switch></Shell></Route></Switch>;
}

function App() { return <QueryClientProvider client={queryClient}><WouterRouter base={import.meta.env.BASE_URL.replace(/\/$/, '')}><ErrorBoundary><AppRouter /></ErrorBoundary></WouterRouter></QueryClientProvider>; }
export default App;